# -*- coding: utf-8 -*-
"""codigo_pcap_para_txt_comeco_mac.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14WQ96pxbUCwRhyfDQIXoSxCvTDy84p45
"""

!pip install -q scapy

from decimal import Decimal
from pathlib import Path

from scapy.all import (
    Ether,
    IP,
    TCP,
    UDP,
    Raw,
    PcapReader,
    raw,
    wrpcap,
)


# CONFIGURAÇÕES

PCAP_FILE = "teste_bia_dani.pcap"
STREAM_FILE = "stream_words.txt"

WORD_BYTES = 8
MAX_PACKETS_TO_SHOW = 7


# FUNÇÕES AXI-STREAM

def timestamp_to_ns(timestamp):
    """Converte segundos para nanossegundos."""

    return int(
        Decimal(str(timestamp))
        * Decimal("1000000000")
    )


def keep_mask(valid_bytes):
    """Gera TKEEP LSB-first."""

    if not 1 <= valid_bytes <= WORD_BYTES:
        raise ValueError(
            f"Quantidade inválida de bytes: {valid_bytes}"
        )

    return (1 << valid_bytes) - 1


def data_to_axi_hex(block):
    """
    Coloca o primeiro byte em tdata[7:0].

    Exemplo:

        01 02 03 04 05 06 07 08
        0807060504030201
    """

    block = block.ljust(
        WORD_BYTES,
        b"\x00",
    )

    return block[::-1].hex().upper()



# GERAÇÃO DO PCAP COM SCAPY

def generate_pcap(filename):

    client_mac = "02:00:00:00:10:01"
    server_mac = "02:00:00:00:20:01"

    client_ip = "192.168.10.10"
    server_ip = "192.168.10.20"

    client_port = 49152
    server_port = 80

    http_request = (
        b"GET /index.html HTTP/1.1\r\n"
        b"Host: exemplo.local\r\n"
        b"Connection: close\r\n"
        b"\r\n"
    )

    http_response = (
        b"HTTP/1.1 200 OK\r\n"
        b"Content-Length: 13\r\n"
        b"Connection: close\r\n"
        b"\r\n"
        b"Hello, World!"
    )

    packets = [

        # TCP SYN
        Ether(src=client_mac, dst=server_mac) /
        IP(src=client_ip, dst=server_ip) /
        TCP(
            sport=client_port,
            dport=server_port,
            seq=1000,
            flags="S",
        ),

        # TCP SYN-ACK
        Ether(src=server_mac, dst=client_mac) /
        IP(src=server_ip, dst=client_ip) /
        TCP(
            sport=server_port,
            dport=client_port,
            seq=2000,
            ack=1001,
            flags="SA",
        ),

        # TCP ACK
        Ether(src=client_mac, dst=server_mac) /
        IP(src=client_ip, dst=server_ip) /
        TCP(
            sport=client_port,
            dport=server_port,
            seq=1001,
            ack=2001,
            flags="A",
        ),

        # Requisição HTTP
        Ether(src=client_mac, dst=server_mac) /
        IP(src=client_ip, dst=server_ip) /
        TCP(
            sport=client_port,
            dport=server_port,
            seq=1001,
            ack=2001,
            flags="PA",
        ) /
        Raw(load=http_request),

        # Resposta HTTP
        Ether(src=server_mac, dst=client_mac) /
        IP(src=server_ip, dst=client_ip) /
        TCP(
            sport=server_port,
            dport=client_port,
            seq=2001,
            ack=1001 + len(http_request),
            flags="PA",
        ) /
        Raw(load=http_response),

        # UDP
        Ether(src=client_mac, dst=server_mac) /
        IP(src=client_ip, dst=server_ip) /
        UDP(
            sport=53000,
            dport=5000,
        ) /
        Raw(load=b"mensagem UDP de teste"),

        # Resposta UDP
        Ether(src=server_mac, dst=client_mac) /
        IP(src=server_ip, dst=client_ip) /
        UDP(
            sport=5000,
            dport=53000,
        ) /
        Raw(load=b"resposta UDP de teste"),
    ]

    # O Scapy gera os cabeçalhos e checksums automaticamente
    wrpcap(filename, packets)

    print(
        f"PCAP criado: {filename}"
    )

    print(
        f"Pacotes criados: {len(packets)}"
    )

# CARACTERÍSTICAS DOS PACOTES

def packet_characteristics(packet):

    info = {
        "protocol": "Não identificado",
        "src_ip": "-",
        "dst_ip": "-",
        "src_port": "-",
        "dst_port": "-",
        "application": "-",
    }

    if packet.haslayer(IP):

        ip = packet[IP]

        info["src_ip"] = ip.src
        info["dst_ip"] = ip.dst

    if packet.haslayer(TCP):

        tcp = packet[TCP]

        info["protocol"] = "TCP"
        info["src_port"] = tcp.sport
        info["dst_port"] = tcp.dport

        if packet.haslayer(Raw):

            payload = bytes(
                packet[Raw].load
            )

            http_prefixes = (
                b"GET ",
                b"POST ",
                b"PUT ",
                b"DELETE ",
                b"HTTP/1.",
            )

            if payload.startswith(
                http_prefixes
            ):
                info["protocol"] = (
                    "HTTP sobre TCP"
                )
                info["application"] = "HTTP"

    elif packet.haslayer(UDP):

        udp = packet[UDP]

        info["protocol"] = "UDP"
        info["src_port"] = udp.sport
        info["dst_port"] = udp.dport

    return info

# CONVERSÃO DO PACOTE PARA AXI-STREAM

def convert(pcap_file):

    if not Path(pcap_file).exists():
        raise FileNotFoundError(
            f"O arquivo {pcap_file} não foi encontrado."
        )

    packet_count = 0
    word_count = 0

    with PcapReader(pcap_file) as pcap, open(
        STREAM_FILE,
        "w",
        encoding="ascii",
    ) as stream:

        # Somente os sinais existentes na interface
        stream.write(
            "# tdata tkeep tvalid tlast tuser\n"
        )

        for packet in pcap:

            packet_count += 1

            captured_data = raw(packet)

            if not captured_data:
                continue

            timestamp_ns = timestamp_to_ns(
                packet.time
            )

            info = packet_characteristics(
                packet
            )

            total_words = (
                len(captured_data)
                + WORD_BYTES
                - 1
            ) // WORD_BYTES

            # Mostra os dados dos pacotes
            if (
                MAX_PACKETS_TO_SHOW is None
                or packet_count
                <= MAX_PACKETS_TO_SHOW
            ):

                print()
                print("=" * 72)
                print(
                    f"PACOTE {packet_count}"
                )
                print("=" * 72)

                print(
                    f"Timestamp (ns): "
                    f"{timestamp_ns}"
                )

                print(
                    f"Protocolo: "
                    f"{info['protocol']}"
                )

                print(
                    f"IP: "
                    f"{info['src_ip']} -> "
                    f"{info['dst_ip']}"
                )

                print(
                    f"Portas: "
                    f"{info['src_port']} -> "
                    f"{info['dst_port']}"
                )

                if info["application"] != "-":
                    print(
                        f"Aplicação: "
                        f"{info['application']}"
                    )

                print()
                print(
                    "Estrutura do pacote:"
                )

                print(
                    packet.show(dump=True)
                )

                print()
                print(
                    "Bytes originais:"
                )

                print(
                    captured_data.hex().upper()
                )

                print()
                print(
                    "Palavras AXI:"
                )

            # Divide o pacote em palavras de 8 bytes
            for word_index in range(total_words):

                start = word_index * WORD_BYTES
                end = start + WORD_BYTES

                block = captured_data[start:end]

                valid_bytes = len(block)

                tdata = data_to_axi_hex(block)

                tkeep = keep_mask(valid_bytes)

                tvalid = 1

                tlast = int(
                    word_index
                    == total_words - 1
                )

                # Conforme a interface utilizada
                tuser = tlast

                stream.write(
                    f"{tdata} "
                    f"{tkeep:02X} "
                    f"{tvalid} "
                    f"{tlast} "
                    f"{tuser}\n"
                )

                if (
                    MAX_PACKETS_TO_SHOW is None
                    or packet_count
                    <= MAX_PACKETS_TO_SHOW
                ):

                    print(
                        f"word {word_index:02d}: "
                        f"{tdata} "
                        f"{tkeep:02X} "
                        f"{tvalid} "
                        f"{tlast} "
                        f"{tuser}"
                    )

                word_count += 1

    print()
    print("Conversão concluída!")
    print(
        f"Arquivo gerado: {STREAM_FILE}"
    )
    print(
        f"Pacotes processados: "
        f"{packet_count}"
    )
    print(
        f"Palavras AXI geradas: "
        f"{word_count}"
    )


# EXECUÇÃO
generate_pcap(PCAP_FILE)
convert(PCAP_FILE)