# -*- coding: utf-8 -*-
"""codigo_PCAP_para_txt_comeco_MAC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B0rSqDZjjAxqsGEie9DkKcCTT03ZPH-0
"""

decimal import Decimal
from pathlib import Path
import ipaddress
import struct
import zipfile

from google.colab import files


# =========================================================
# Upload do arquivo PCAP
# =========================================================

uploaded = files.upload()

pcap_files = [
    nome
    for nome in uploaded.keys()
    if nome.lower().endswith(".pcap")
]

if not pcap_files:
    raise FileNotFoundError(
        "Nenhum arquivo .pcap foi enviado."
    )

PCAP_FILE = pcap_files[0]

print("Arquivo selecionado:", PCAP_FILE)


# =========================================================
# Arquivos gerados
# =========================================================

STREAM_FILE = "stream_words.txt"
METADATA_FILE = "packet_metadata.txt"
STREAM_DETAILS_FILE = "stream_words_detalhado.txt"
PACKET_DETAILS_FILE = "packet_details.txt"
ZIP_FILE = "relatorios_mac_rx.zip"

WORD_BYTES = 8


# Tipos de enlace
DLT_NULL = 0
DLT_EN10MB = 1


# Endereços MAC sintéticos para transformar DLT_NULL em Ethernet II
# O PCAP foi capturado usando DLT_NULL (LINKTYPE_NULL=0),
# formato utilizado em interfaces de loopback.
# Como esse formato não possui cabeçalho Ethernet com endereços MAC,
# criamos endereços MAC sintéticos para montar um quadro Ethernet II.
#
# 0x02 = 00000010:
# bit 0 = 0 -> endereço unicast
# bit 1 = 1 -> endereço localmente administrado
#
# Esses MACs são usados somente na simulação e não representam
# endereços físicos reais capturados no Wireshark.
DEST_MAC = bytes.fromhex("020000000002")
SOURCE_MAC = bytes.fromhex("020000000001")


# =========================================================
# Importação opcional do Scapy
# =========================================================

try:
    from scapy.all import PcapReader as ScapyPcapReader
    from scapy.all import raw as scapy_raw

except Exception:
    ScapyPcapReader = None
    scapy_raw = None


# =========================================================
# Conversão de timestamp
# =========================================================

def timestamp_to_ns(timestamp):
    """
    Converte segundos para nanossegundos.
    """

    return int(
        Decimal(str(timestamp))
        * Decimal("1000000000")
    )


# =========================================================
# Geração do tkeep
# =========================================================

def keep_mask(valid_bytes, word_bytes=WORD_BYTES):
    """
    Gera tkeep no formato LSB-first.

    1 byte  -> 01
    2 bytes -> 03
    3 bytes -> 07
    4 bytes -> 0F
    5 bytes -> 1F
    6 bytes -> 3F
    7 bytes -> 7F
    8 bytes -> FF
    """

    if valid_bytes < 1 or valid_bytes > word_bytes:
        raise ValueError(
            "Quantidade de bytes inválida."
        )

    return (1 << valid_bytes) - 1


# =========================================================
# Conversão para tdata
# =========================================================

def data_to_axi_hex(block, word_bytes=WORD_BYTES):
    """
    O primeiro byte ocupa tdata[7:0].

    Exemplo:

        bytes: 01 02 03 04 05 06 07 08
        tdata: 0807060504030201
    """

    padded_block = block.ljust(
        word_bytes,
        b"\x00"
    )

    return padded_block[::-1].hex().upper()


# =========================================================
# Leitura de PCAP usando a biblioteca padrão
# =========================================================

def read_pcap_stdlib(filename):
    """
    Lê um arquivo PCAP clássico.

    Retorna:

        timestamp
        bytes do pacote
        tipo de enlace
    """

    with open(filename, "rb") as capture:

        global_header = capture.read(24)

        if len(global_header) != 24:
            raise ValueError(
                "Cabeçalho PCAP incompleto."
            )

        magic = global_header[:4]

        formats = {
            b"\xd4\xc3\xb2\xa1": ("<", 6),
            b"\xa1\xb2\xc3\xd4": (">", 6),
            b"\x4d\x3c\xb2\xa1": ("<", 9),
            b"\xa1\xb2\x3c\x4d": (">", 9),
        }

        if magic not in formats:
            raise ValueError(
                "Formato PCAP não reconhecido."
            )

        endian, fractional_digits = formats[magic]

        link_type = struct.unpack(
            endian + "I",
            global_header[20:24]
        )[0]

        packet_header = struct.Struct(
            endian + "IIII"
        )

        while True:

            header = capture.read(
                packet_header.size
            )

            if not header:
                break

            if len(header) != packet_header.size:
                raise ValueError(
                    "Cabeçalho do pacote incompleto."
                )

            (
                seconds,
                fraction,
                captured_length,
                original_length
            ) = packet_header.unpack(header)

            data = capture.read(
                captured_length
            )

            if len(data) != captured_length:
                raise ValueError(
                    "Dados do pacote incompletos."
                )

            timestamp = (
                f"{seconds}."
                f"{fraction:0{fractional_digits}d}"
            )

            yield (
                timestamp,
                data,
                link_type
            )


# =========================================================
# Leitura geral da captura
# =========================================================

def iter_capture(filename):
    """
    Lê a captura e retorna:

        timestamp
        bytes do pacote
        tipo de enlace
    """

    try:
        yield from read_pcap_stdlib(filename)
        return

    except (
        OSError,
        ValueError,
        struct.error
    ):
        pass

    if ScapyPcapReader is None:
        raise RuntimeError(
            "Não foi possível ler o arquivo PCAP."
        )

    try:

        with ScapyPcapReader(filename) as pcap:

            for packet in pcap:

                frame = scapy_raw(packet)

                if frame:
                    yield (
                        str(packet.time),
                        frame,
                        None
                    )

    except (
        OSError,
        PermissionError,
        RuntimeError
    ) as error:

        raise RuntimeError(
            f"Falha ao ler o arquivo: {filename}"
        ) from error


# =========================================================
# Identificação da família do DLT_NULL
# =========================================================

def null_family(frame):
    """
    Identifica a família de rede do cabeçalho DLT_NULL.

    IPv4 -> família 2
    IPv6 -> família 24
    """

    if len(frame) < 4:
        raise ValueError(
            "Quadro DLT_NULL menor que 4 bytes."
        )

    family_little = int.from_bytes(
        frame[:4],
        "little"
    )

    family_big = int.from_bytes(
        frame[:4],
        "big"
    )

    known_families = {
        2,
        24,
        28,
        30
    }

    if family_little in known_families:
        return family_little

    if family_big in known_families:
        return family_big

    raise ValueError(
        "Família DLT_NULL não suportada: "
        f"{family_little} / {family_big}"
    )


# =========================================================
# Conversão DLT_NULL para Ethernet II
# =========================================================

def normalize_frame(frame, link_type):
    """
    Converte o quadro para Ethernet II.

    Para DLT_EN10MB:
        o quadro já é Ethernet.

    Para DLT_NULL:
        remove os 4 bytes do cabeçalho Loopback
        e adiciona um cabeçalho Ethernet II.
    """

    # O quadro já está no formato Ethernet
    if link_type in (
        None,
        DLT_EN10MB
    ):
        return frame, None

    if link_type != DLT_NULL:
        raise ValueError(
            f"Tipo de enlace DLT_{link_type} "
            "não suportado."
        )

    family = null_family(frame)

    # Remove o cabeçalho Loopback
    ip_packet = frame[4:]

    if len(ip_packet) == 0:
        raise ValueError(
            "Pacote IP vazio."
        )

    version = ip_packet[0] >> 4

    # EtherType IPv4
    if family == 2 or version == 4:
        ether_type = b"\x08\x00"

    # EtherType IPv6
    elif family in (
        24,
        28,
        30
    ) or version == 6:
        ether_type = b"\x86\xDD"

    else:
        raise ValueError(
            "Versão IP não reconhecida."
        )

    ethernet_header = (
        DEST_MAC
        + SOURCE_MAC
        + ether_type
    )

    return (
        ethernet_header + ip_packet,
        family
    )


# =========================================================
# Características dos pacotes
# =========================================================

def frame_characteristics(frame):
    """
    Extrai:

        EtherType
        versão IP
        protocolo
        IP de origem
        IP de destino
        porta de origem
        porta de destino
    """

    info = {
        "ethertype": "-",
        "ip_version": "-",
        "protocol": "-",
        "src_ip": "-",
        "dst_ip": "-",
        "src_port": "-",
        "dst_port": "-"
    }

    # Ethernet possui pelo menos 14 bytes
    if len(frame) < 14:
        return info

    ethertype = int.from_bytes(
        frame[12:14],
        "big"
    )

    info["ethertype"] = (
        f"0x{ethertype:04X}"
    )

    ip_offset = 14
    l4_offset = None

    # =========================
    # IPv4
    # =========================

    if (
        ethertype == 0x0800
        and len(frame) >= 34
    ):

        info["ip_version"] = "IPv4"

        ihl = (
            frame[ip_offset]
            & 0x0F
        ) * 4

        if ihl < 20:
            return info

        if len(frame) < ip_offset + ihl:
            return info

        protocol_number = frame[23]

        info["src_ip"] = str(
            ipaddress.ip_address(
                frame[26:30]
            )
        )

        info["dst_ip"] = str(
            ipaddress.ip_address(
                frame[30:34]
            )
        )

        l4_offset = ip_offset + ihl

    # =========================
    # IPv6
    # =========================

    elif (
        ethertype == 0x86DD
        and len(frame) >= 54
    ):

        info["ip_version"] = "IPv6"

        protocol_number = frame[20]

        info["src_ip"] = str(
            ipaddress.ip_address(
                frame[22:38]
            )
        )

        info["dst_ip"] = str(
            ipaddress.ip_address(
                frame[38:54]
            )
        )

        l4_offset = 54

    else:
        return info

    protocol_names = {
        1: "ICMP",
        6: "TCP",
        17: "UDP",
        58: "ICMPv6"
    }

    info["protocol"] = protocol_names.get(
        protocol_number,
        f"PROTOCOLO_{protocol_number}"
    )

    # TCP ou UDP possuem portas
    if (
        protocol_number in (6, 17)
        and l4_offset is not None
        and len(frame) >= l4_offset + 4
    ):

        info["src_port"] = str(
            int.from_bytes(
                frame[
                    l4_offset:
                    l4_offset + 2
                ],
                "big"
            )
        )

        info["dst_port"] = str(
            int.from_bytes(
                frame[
                    l4_offset + 2:
                    l4_offset + 4
                ],
                "big"
            )
        )

    return info


# =========================================================
# Conversão completa
# =========================================================

def convert(pcap_file):

    packet_count = 0
    word_count = 0

    with open(
        STREAM_FILE,
        "w",
        encoding="ascii"
    ) as stream, open(
        METADATA_FILE,
        "w",
        encoding="ascii"
    ) as metadata, open(
        STREAM_DETAILS_FILE,
        "w",
        encoding="utf-8"
    ) as stream_details, open(
        PACKET_DETAILS_FILE,
        "w",
        encoding="utf-8"
    ) as packet_details:

        # Arquivo usado pela testbench
        stream.write(
            "# tdata tkeep tvalid tlast tuser\n"
        )

        # Um registro por pacote
        metadata.write(
            "# packet_id "
            "timestamp_ns "
            "captured_bytes "
            "stream_bytes "
            "link_type "
            "family\n"
        )

        # Uma linha por palavra AXI
        stream_details.write(
            "# packet_id\t"
            "timestamp_ns\t"
            "word_index\t"
            "total_words\t"
            "captured_bytes\t"
            "stream_bytes\t"
            "family\t"
            "ethertype\t"
            "ip_version\t"
            "protocol\t"
            "src_ip\t"
            "dst_ip\t"
            "src_port\t"
            "dst_port\t"
            "tdata\t"
            "tkeep\t"
            "valid_bytes\t"
            "tvalid\t"
            "tlast\t"
            "tuser\n"
        )

        # Uma linha por pacote
        packet_details.write(
            "# packet_id\t"
            "timestamp_ns\t"
            "captured_bytes\t"
            "stream_bytes\t"
            "link_type\t"
            "family\t"
            "ethertype\t"
            "ip_version\t"
            "protocol\t"
            "src_ip\t"
            "dst_ip\t"
            "src_port\t"
            "dst_port\t"
            "captured_hex\t"
            "stream_hex\n"
        )

        # Processa cada pacote do PCAP
        for (
            timestamp,
            captured_frame,
            link_type
        ) in iter_capture(pcap_file):

            if not captured_frame:
                continue

            # Converte para Ethernet II
            frame, family = normalize_frame(
                captured_frame,
                link_type
            )

            packet_count += 1

            timestamp_ns = timestamp_to_ns(
                timestamp
            )

            characteristics = frame_characteristics(
                frame
            )

            family_text = (
                "-"
                if family is None
                else str(family)
            )

            link_type_text = (
                "-"
                if link_type is None
                else str(link_type)
            )

            # Salva metadados básicos
            metadata.write(
                f"{packet_count} "
                f"{timestamp_ns} "
                f"{len(captured_frame)} "
                f"{len(frame)} "
                f"{link_type_text} "
                f"{family_text}\n"
            )

            # Salva informações completas do pacote
            packet_details.write(
                f"{packet_count}\t"
                f"{timestamp_ns}\t"
                f"{len(captured_frame)}\t"
                f"{len(frame)}\t"
                f"{link_type_text}\t"
                f"{family_text}\t"
                f"{characteristics['ethertype']}\t"
                f"{characteristics['ip_version']}\t"
                f"{characteristics['protocol']}\t"
                f"{characteristics['src_ip']}\t"
                f"{characteristics['dst_ip']}\t"
                f"{characteristics['src_port']}\t"
                f"{characteristics['dst_port']}\t"
                f"{captured_frame.hex().upper()}\t"
                f"{frame.hex().upper()}\n"
            )

            # Calcula o número de palavras de 64 bits
            total_words = (
                len(frame)
                + WORD_BYTES
                - 1
            ) // WORD_BYTES

            # Divide o pacote em palavras de 8 bytes
            for word_index in range(total_words):

                inicio = word_index * WORD_BYTES
                fim = inicio + WORD_BYTES

                bloco = frame[inicio:fim]

                valid_bytes = len(bloco)

                tdata = data_to_axi_hex(
                    bloco
                )

                tkeep = keep_mask(
                    valid_bytes
                )

                tvalid = 1

                tlast = int(
                    word_index
                    == total_words - 1
                )

                tuser = tlast

                # Arquivo padrão para a testbench
                stream.write(
                    f"{tdata} "
                    f"{tkeep:02X} "
                    f"{tvalid} "
                    f"{tlast} "
                    f"{tuser}\n"
                )

                # Arquivo detalhado por palavra
                stream_details.write(
                    f"{packet_count}\t"
                    f"{timestamp_ns}\t"
                    f"{word_index}\t"
                    f"{total_words}\t"
                    f"{len(captured_frame)}\t"
                    f"{len(frame)}\t"
                    f"{family_text}\t"
                    f"{characteristics['ethertype']}\t"
                    f"{characteristics['ip_version']}\t"
                    f"{characteristics['protocol']}\t"
                    f"{characteristics['src_ip']}\t"
                    f"{characteristics['dst_ip']}\t"
                    f"{characteristics['src_port']}\t"
                    f"{characteristics['dst_port']}\t"
                    f"{tdata}\t"
                    f"{tkeep:02X}\t"
                    f"{valid_bytes}\t"
                    f"{tvalid}\t"
                    f"{tlast}\t"
                    f"{tuser}\n"
                )

                word_count += 1

    return packet_count, word_count


# =========================================================
# Execução
# =========================================================

packet_count, word_count = convert(
    PCAP_FILE
)


print()
print("Conversão concluída!")
print("Pacotes:", packet_count)
print("Palavras AXI:", word_count)
print("Arquivo da testbench:", STREAM_FILE)
print("Metadados:", METADATA_FILE)
print("Detalhamento por palavra:", STREAM_DETAILS_FILE)
print("Detalhamento por pacote:", PACKET_DETAILS_FILE)


# =========================================================
# Compactação para download
# =========================================================

with zipfile.ZipFile(
    ZIP_FILE,
    "w",
    zipfile.ZIP_DEFLATED
) as arquivo_zip:

    for nome in [
        STREAM_FILE,
        METADATA_FILE,
        STREAM_DETAILS_FILE,
        PACKET_DETAILS_FILE
    ]:

        if Path(nome).exists():
            arquivo_zip.write(
                nome,
                arcname=nome
            )


print("Arquivo compactado:", ZIP_FILE)

files.download(ZIP_FILE)